<?php

    session_start();

    require_once 'Auth/Yubico.php';

    if (isset($_POST['submit'])) {
			
        $otp = $_POST['yubi_otp'];
        $identity = substr($otp, 0, 12);
			
        # We set the valid keys here
        # Get your API key from:
        #     https://upgrade.yubico.com/getapikey/
        # And then put it in below in the format:
        # username  Identity:ClientID:Secret key
        #
        # Identity comes from the first 12 letters of a OTP generated by the key
        # and saves us talking to Yubi unless we have a valid OTP.
        # 
        # Add one line for each key you'd like to allow access too - usernames
        # can be duplicated.  You could put this in a database if you so wish...

        $allowed_users['andrew'] = "ccccccabcdef:12345:0oHCEE9C0ffeeC0feefeswkr7HU=";
        $allowed_users['freddy'] = "dddddddddddd:12321:0oHCE7ekdmdsaewDD312DDASWHU=";
        $allowed_users['twinkl'] = "ccccccbbbaab:32123:0o342ajkh4jk2hdsaljkh321das=";

        foreach($allowed_users as $username=>$yubi_secret) {

            $yubi = explode(":", $yubi_secret);
            $yubi_id = $yubi[0];
            $client_id = $yubi[1];
            $secret_key = $yubi[2];

            if ($identity == $yubi_id) {

                $yubi_auth = new Auth_Yubico($client_id, $secret_key);
                $auth = $yubi_auth->verify($otp);

                if (PEAR::isError($auth)) {

                    $_SESSION["error"] = $yubi_auth->getLastResponse();

                } else {

                    $_SESSION["key"]= $identity;	
                    $_SESSION["userid"] = $username;

                    // We have authenticated
				
                    header("location: index.php");
                    exit;
               }
           }
       }
    }


    // If we have got here we have not authenticated  :(

    header("location: login.php");

?>
